name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client

      - name: Build and push server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server

      - name: Build and push worker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker

      - name: Build and push nginx
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
