name: CI (client tests)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build client test image
        run: docker build -t react-test -f ./client/Dockerfile.dev ./client

      - name: Run client tests
        run: docker run --rm react-test npm test -- --coverage
